package org.sakila.videostore.jpa.entities;
// Generated 7 jul 2024 11:26:27 by Hibernate Tools 6.5.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="sakila"
)
public class City extends io.quarkus.hibernate.orm.panache.PanacheEntityBase {


     private Short cityId;
     private Country country;
     private String city;
     private Timestamp lastUpdate;

    public City() {
    }

    public City(Country country, String city, Timestamp lastUpdate) {
       this.country = country;
       this.city = city;
       this.lastUpdate = lastUpdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="city_id", unique=true, nullable=false)
    public Short getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="city", nullable=false, length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}
